services:
#  nginx-proxy-2026:
#    container_name: nginx-proxy-2026
#    build: ./docker/builds/nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./certs:/etc/nginx/certs

  backend-2026:
    container_name: backend-2026
    build: ./docker/builds/backend-2026
    volumes:
      - ./backend:/var/www/html/backend
    working_dir: /var/www/html/backend
    ports:
      - "8080:80"
    depends_on:
      - phpfpm85-2026

  phpfpm85-2026:
    container_name: phpfpm85-2026
    build: ./docker/builds/phpfpm85
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/backend
    links:
      - mariadb-2026

  phpfpm85-2026-command:
    container_name: phpfpm85-2026-command
    build: ./docker/builds/phpfpm85-command
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/backend
    links:
      - mariadb-2026

  mariadb-2026:
    image: mariadb:12.3.2
    container_name: mariadb-2026
    ports:
      - "33061:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./dumps:/var/lib/mysql/dumps
    working_dir: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root